spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: false
server:
  port: 8761