spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lwsh1995/config-server
          basedir: E:\idea\java\cloud\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8703

management:
  endpoints:
    web:
      exposure:
        include: "*"